//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JpkHelper.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JpkHelper.Localisation.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przygotowywuje plik InitUpload.xml oraz szyfruje pliki podlegające wysyłce.
        /// </summary>
        public static string MakeCommandHelpText {
            get {
                return ResourceManager.GetString("MakeCommandHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy pokazać wygenerowany klucz symetryczny AES.
        /// </summary>
        public static string MakeManifestAESKeyBehaviourProperty {
            get {
                return ResourceManager.GetString("MakeManifestAESKeyBehaviourProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka do pliku z certyfikatem publicznym ministerstwa. Jeśli argument nie zostanie podany, program wybierze klucz na podstawie środowiska i zapisanych danych.
        /// </summary>
        public static string MakeManifestCertificateFileProperty {
            get {
                return ResourceManager.GetString("MakeManifestCertificateFileProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ środowiska.
        /// </summary>
        public static string MakeManifestEnviromentTypeProperty {
            get {
                return ResourceManager.GetString("MakeManifestEnviromentTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przerwij pracę jeśli certyfikat jest przeterminowany.
        /// </summary>
        public static string MakeManifestFailOnExpiredCertificateProperty {
            get {
                return ResourceManager.GetString("MakeManifestFailOnExpiredCertificateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki xml które mają podlegać wysyłce.
        /// </summary>
        public static string MakeManifestFilesProperty {
            get {
                return ResourceManager.GetString("MakeManifestFilesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wyświetlaj tekstu pomocy na temat wysyłki przygotowanych plików..
        /// </summary>
        public static string MakeManifestNoHelpTextProperty {
            get {
                return ResourceManager.GetString("MakeManifestNoHelpTextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder w którym umieszczony zostanie wynik operacji.
        /// </summary>
        public static string MakeManifestOutputPathProperty {
            get {
                return ResourceManager.GetString("MakeManifestOutputPathProperty", resourceCulture);
            }
        }
    }
}
