//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JpkHelper.Localisation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JpkHelper.Localisation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AesKey {
            get {
                return ResourceManager.GetString("AesKey", resourceCulture);
            }
        }
        
        public static string CertificateExpiredWarning {
            get {
                return ResourceManager.GetString("CertificateExpiredWarning", resourceCulture);
            }
        }
        
        public static string CertificateNotSaved {
            get {
                return ResourceManager.GetString("CertificateNotSaved", resourceCulture);
            }
        }
        
        public static string FilesReadyToSend {
            get {
                return ResourceManager.GetString("FilesReadyToSend", resourceCulture);
            }
        }
        
        public static string SavingBase64AesKey {
            get {
                return ResourceManager.GetString("SavingBase64AesKey", resourceCulture);
            }
        }
        
        public static string ToSendEnterFollowingCommand {
            get {
                return ResourceManager.GetString("ToSendEnterFollowingCommand", resourceCulture);
            }
        }
        
        public static string ValidatingFile {
            get {
                return ResourceManager.GetString("ValidatingFile", resourceCulture);
            }
        }
        
        public static string ValidationErrorMessage {
            get {
                return ResourceManager.GetString("ValidationErrorMessage", resourceCulture);
            }
        }
        
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
    }
}
