//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JpkHelper.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JpkHelper.Localisation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES key (base64 encoded): {0}.
        /// </summary>
        internal static string AesKey {
            get {
                return ResourceManager.GetString("AesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWAGA: certyfikat używany do szyfrowania klucza symetrczynego wygasł.
        /// </summary>
        internal static string CertificateExpiredWarning {
            get {
                return ResourceManager.GetString("CertificateExpiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certyfikat dla tego środowiska nie został zapisany w programie. Użyj opcji --certificate-file aby sprecyzować pobrany przez siebie certyfikat.
        /// </summary>
        internal static string CertificateNotSaved {
            get {
                return ResourceManager.GetString("CertificateNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakiet plików gotowy do wysyłki w folderze &quot;{0}&quot;.
        /// </summary>
        internal static string FilesReadyToSend {
            get {
                return ResourceManager.GetString("FilesReadyToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisuję klucz AES (base64 encoded) do pliku {0}.
        /// </summary>
        internal static string SavingBase64AesKey {
            get {
                return ResourceManager.GetString("SavingBase64AesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby dokonać wysyłki, wywołaj ten program ponownie w następujący sposób:.
        /// </summary>
        internal static string ToSendEnterFollowingCommand {
            get {
                return ResourceManager.GetString("ToSendEnterFollowingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weryfikuję spójność pliku: {0}.
        /// </summary>
        internal static string ValidatingFile {
            get {
                return ResourceManager.GetString("ValidatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weryfikacja pliku {0} niepowiodła się: {1}.
        /// </summary>
        internal static string ValidationErrorMessage {
            get {
                return ResourceManager.GetString("ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weryfikacja niepowiodła się.
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
    }
}
